CREATE TABLE     TSEAIHS03(
        COLUMNNAME VARCHAR2(40) NOT NULL,
        COLUMNDESC VARCHAR2(200),
        COLUMNLENGTH NUMBER,
        ISKEY VARCHAR2(1),
        KEYSEQ NUMBER,
        ISINTERFACE VARCHAR2(1),
        COMBONAME VARCHAR2(40),
        COMBODEPTH NUMBER,
        COLUMNDEFAULT VARCHAR2(200)
);

CREATE TABLE TSEAIHS04(
        BZWKSVCKEYNAME VARCHAR2(40) NOT NULL,
        EAISVCNAME VARCHAR2(40)
);

CREATE TABLE TSEAIHS05(
        BZWKSVCKEYNAME VARCHAR2(40) NOT NULL,
        COLUMNNAME VARCHAR2(40) NOT NULL,
        COLUMNVALUE VARCHAR2(200)
);

INSERT INTO TSEAIHS03 (COLUMNNAME, COLUMNDESC, COLUMNLENGTH, ISKEY, KEYSEQ, ISINTERFACE, COMBONAME, COMBODEPTH, COLUMNDEFAULT) VALUES ('HEADER_MESGDMANDVCD', '전문요청구분코드', 1, 'Y', 2, 'N', null, null, null);
INSERT INTO TSEAIHS03 (COLUMNNAME, COLUMNDESC, COLUMNLENGTH, ISKEY, KEYSEQ, ISINTERFACE, COMBONAME, COMBODEPTH, COLUMNDEFAULT) VALUES ('COMMON_GROUPCMPCD', '그룹회사코드', 3, 'N', 0, 'N', null, null, '034');
INSERT INTO TSEAIHS03 (COLUMNNAME, COLUMNDESC, COLUMNLENGTH, ISKEY, KEYSEQ, ISINTERFACE, COMBONAME, COMBODEPTH, COLUMNDEFAULT) VALUES ('COMMON_SRVCID', '서비스ID', 11, 'N', 0, 'N', null, null, null);
INSERT INTO TSEAIHS03 (COLUMNNAME, COLUMNDESC, COLUMNLENGTH, ISKEY, KEYSEQ, ISINTERFACE, COMBONAME, COMBODEPTH, COLUMNDEFAULT) VALUES ('COMMON_PROCSRSLTRCMSSRVCID', '처리결과수신서비스ID', 11, 'N', 0, 'N', null, null, null);
INSERT INTO TSEAIHS03 (COLUMNNAME, COLUMNDESC, COLUMNLENGTH, ISKEY, KEYSEQ, ISINTERFACE, COMBONAME, COMBODEPTH, COLUMNDEFAULT) VALUES ('COMMON_IFID', '인터페이스ID', 20, 'Y', 1, 'Y', null, null, null);
INSERT INTO TSEAIHS03 (COLUMNNAME, COLUMNDESC, COLUMNLENGTH, ISKEY, KEYSEQ, ISINTERFACE, COMBONAME, COMBODEPTH, COLUMNDEFAULT) VALUES ('COMMON_OTSDCHNLINSTCD', '대외채널기관코드', 3, 'N', 0, 'N', null, null, null);
INSERT INTO TSEAIHS03 (COLUMNNAME, COLUMNDESC, COLUMNLENGTH, ISKEY, KEYSEQ, ISINTERFACE, COMBONAME, COMBODEPTH, COLUMNDEFAULT) VALUES ('COMMON_HMABDVCD', '내외구분코드', 1, 'Y', 3, 'N', null, null, null);
INSERT INTO TSEAIHS03 (COLUMNNAME, COLUMNDESC, COLUMNLENGTH, ISKEY, KEYSEQ, ISINTERFACE, COMBONAME, COMBODEPTH, COLUMNDEFAULT) VALUES ('COMMON_ORTRRESTRYN', '원거래복원여부', 1, 'N', 0, 'N', null, null, '  ');
INSERT INTO TSEAIHS03 (COLUMNNAME, COLUMNDESC, COLUMNLENGTH, ISKEY, KEYSEQ, ISINTERFACE, COMBONAME, COMBODEPTH, COLUMNDEFAULT) VALUES ('COMMON_SYSOPRTENVDVCD', '시스템운영환경구분코드', 1, 'N', 0, 'N', null, null, 'D');
INSERT INTO TSEAIHS03 (COLUMNNAME, COLUMNDESC, COLUMNLENGTH, ISKEY, KEYSEQ, ISINTERFACE, COMBONAME, COMBODEPTH, COLUMNDEFAULT) VALUES ('COMMON_CHNLTYCD', '채널유형코드', 1, 'N', 0, 'N', null, null, null);
INSERT INTO TSEAIHS03 (COLUMNNAME, COLUMNDESC, COLUMNLENGTH, ISKEY, KEYSEQ, ISINTERFACE, COMBONAME, COMBODEPTH, COLUMNDEFAULT) VALUES ('COMMON_CHNLDTLSCLCD', '채널세부분류코드', 3, 'N', 0, 'N', null, null, null);
INSERT INTO TSEAIHS03 (COLUMNNAME, COLUMNDESC, COLUMNLENGTH, ISKEY, KEYSEQ, ISINTERFACE, COMBONAME, COMBODEPTH, COLUMNDEFAULT) VALUES ('COMMON_SCNNO', '화면번호', 13, 'N', 0, 'N', null, null, null);
INSERT INTO TSEAIHS03 (COLUMNNAME, COLUMNDESC, COLUMNLENGTH, ISKEY, KEYSEQ, ISINTERFACE, COMBONAME, COMBODEPTH, COLUMNDEFAULT) VALUES ('COMMON_TXBRCD', '거래부점코드', 4, 'N', 0, 'N', null, null, '0100');
INSERT INTO TSEAIHS03 (COLUMNNAME, COLUMNDESC, COLUMNLENGTH, ISKEY, KEYSEQ, ISINTERFACE, COMBONAME, COMBODEPTH, COLUMNDEFAULT) VALUES ('COMMON_RLTRBRCD', '실거래점코드', 4, 'N', 0, 'N', null, null, '0100');
INSERT INTO TSEAIHS03 (COLUMNNAME, COLUMNDESC, COLUMNLENGTH, ISKEY, KEYSEQ, ISINTERFACE, COMBONAME, COMBODEPTH, COLUMNDEFAULT) VALUES ('COMMON_TLRNO', '텔러번호', 6, 'N', 0, 'N', null, null, '000000');


insert into tseaihs04 (select "BzwkSvcKeyName","EAITranName"||"SplizDmndDstcd"||"StndTelgmWtinExtnlDstcd" FROM TSEAIHS01);
insert into tseaihs05 (select "BzwkSvcKeyName",'COMMON_CHNLDTLSCLCD',"ChnlDvDstcd" FROM TSEAIHS01);
insert into tseaihs05 (select "BzwkSvcKeyName",'COMMON_CHNLTYCD',"ChnlDstcd" FROM TSEAIHS01);
insert into tseaihs05 (select "BzwkSvcKeyName",'COMMON_GROUPCMPCD',"GroupCoNo" FROM TSEAIHS01);
insert into tseaihs05 (select "BzwkSvcKeyName",'COMMON_HMABDVCD',"StndTelgmWtinExtnlDstcd" FROM TSEAIHS01);
insert into tseaihs05 (select "BzwkSvcKeyName",'COMMON_IFID',"EAITranName" FROM TSEAIHS01);
insert into tseaihs05 (select "BzwkSvcKeyName",'COMMON_ORTRRESTRYN',"OgtranRstrYn" FROM TSEAIHS01);
insert into tseaihs05 (select "BzwkSvcKeyName",'COMMON_OTSDCHNLINSTCD',"OsidInstiNo" FROM TSEAIHS01);
insert into tseaihs05 (select "BzwkSvcKeyName",'COMMON_PROCSRSLTRCMSSRVCID',"PrcssRsultRecvTranNo" FROM TSEAIHS01);
insert into tseaihs05 (select "BzwkSvcKeyName",'COMMON_RLTRBRCD',"TranBrncd" FROM TSEAIHS01);
insert into tseaihs05 (select "BzwkSvcKeyName",'COMMON_SCNNO',"ScrenDsticIdnfr" FROM TSEAIHS01);
insert into tseaihs05 (select "BzwkSvcKeyName",'COMMON_SRVCID',"RecvTranName" FROM TSEAIHS01);
insert into tseaihs05 (select "BzwkSvcKeyName",'COMMON_SYSOPRTENVDVCD',"SysOperEvirnDstcd" FROM TSEAIHS01);
insert into tseaihs05 (select "BzwkSvcKeyName",'COMMON_TLRNO',"UserEmpid" FROM TSEAIHS01);
insert into tseaihs05 (select "BzwkSvcKeyName",'COMMON_TXBRCD',"TranBrncd" FROM TSEAIHS01);
insert into tseaihs05 (select "BzwkSvcKeyName",'HEADER_MESGDMANDVCD',"SplizDmndDstcd" FROM TSEAIHS01);


