version: '2'
services:
  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8080:8080"
    extra_hosts:
      - 'DESKTOP-NF2S1OK:192.168.10.87'  
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=192.168.10.87:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=192.168.10.87:2181