
select * from INST1.TSEAIST01;
select * from INST2.TSEAIST01;
select * from INST3.TSEAIST01;

SELECT * FROM INST1.TSEAIST02;
SELECT * FROM INST2.TSEAIST02;
SELECT * FROM INST3.TSEAIST02;
        
DELETE FROM   "INST1"."TSEAIST01";     
DELETE FROM   "INST2"."TSEAIST01" ;        
DELETE FROM   "INST3"."TSEAIST01";

DELETE FROM "INST1".TSEAIST02;
DELETE FROM "INST2"."TSEAIST02" ;        
DELETE FROM "INST3"."TSEAIST02";

commit;
